name: instagram_exercise
description: A new Flutter project.
publish_to: 'none'
#1
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
#2
dependencies:
  flutter:
    sdk: flutter
#3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#4    
  flutter_lints: ^2.0.0
#5    
flutter:
# assets 폴더의 모든 이미지를 불러옴
  uses-material-design: true
  assets:     # 새로 추가한 부분
    - assets/ # assets 폴더의 모든 이미지를 불러옴